# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix: {python: ["3.11", "3.12"]}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: ${{ matrix.python }}}
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py${{ matrix.python }}-${{ hashFiles('**/poetry.lock') }}
      - run: pip install poetry
      - run: poetry install --with dev
      - name: Ruff + MyPy + Bandit
        run: |
          poetry run ruff check .
          poetry run mypy .
          poetry run bandit -r src
      - name: Run pytest + coverage
        run: poetry run pytest -q --cov=src
